/**
 * Plain HTML Code Generator
 */

import type { Block, Page, Design } from '@open-design/blocks';
import { BaseCodeGenerator } from './base-generator.js';
import {
  generateHTML,
  extractTailwindClasses,
} from '../utils/code-utils.js';
import { injectHtmlBlockIds } from '../utils/block-id-injection.js';
import type { CodeGenerationResult, FrameworkTarget } from '../types/index.js';

/**
 * Plain HTML code generator
 */
export class HtmlCodeGenerator extends BaseCodeGenerator {
  readonly framework: FrameworkTarget = 'html';

  /**
   * Generate code for a single page
   */
  generatePage(page: Page): CodeGenerationResult {
    const fileName = this.generateFilePath(page.name, '.html');
    
    // Generate HTML
    const htmlContent = this.generateHtmlPage(page.blocks, page.name);
    
    return {
      files: [
        this.createFile(fileName, htmlContent, 'html'),
      ],
      entryFile: fileName,
      framework: 'html',
    };
  }

  /**
   * Generate code for a full design
   */
  generateDesign(design: Design): CodeGenerationResult {
    const files: GeneratedFile[] = [];
    
    // Generate each page
    for (const page of design.pages) {
      const pageResult = this.generatePage(page);
      files.push(...pageResult.files);
    }
    
    // Generate index.html (home page or first page)
    const homePage = design.pages.find(p => p.slug === 'home') || design.pages[0];
    if (homePage) {
      const indexHtml = this.generateHtmlPage(homePage.blocks, design.name);
      files.push(this.createFile('index.html', indexHtml, 'html'));
    }
    
    // Generate styles.css
    const stylesCss = this.generateStylesCss();
    files.push(this.createFile('styles.css', stylesCss, 'css'));
    
    // Generate README.md
    const readme = this.generateReadme(design.name);
    files.push(this.createFile('README.md', readme, 'markdown'));
    
    return {
      files,
      entryFile: 'index.html',
      framework: 'html',
    };
  }

  /**
   * Generate code for a single block
   */
  generateBlock(block: Block): string {
    return generateHTML([block]);
  }

  /**
   * Generate HTML page
   */
  private generateHtmlPage(blocks: Block[], title: string): string {
    let bodyContent = generateHTML(blocks, 4);
    
    // Inject block IDs for visual editing
    bodyContent = injectHtmlBlockIds(bodyContent, blocks);
    
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <main>
${bodyContent}
  </main>
</body>
</html>
`;
  }

  /**
   * Generate styles.css
   */
  private generateStylesCss(): string {
    return `/* Custom styles */
:root {
  --bg: #ffffff;
  --surface: #ffffff;
  --fg: #111827;
  --muted: #6b7280;
  --border: #e5e7eb;
  --accent: #3b82f6;
  --accent-on: #ffffff;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: system-ui, -apple-system, sans-serif;
  background-color: var(--bg);
  color: var(--fg);
  line-height: 1.6;
}

main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}
`;
  }

  /**
   * Generate README.md
   */
  private generateReadme(projectName: string): string {
    return `# ${projectName}

Generated by Open Design

## Usage

Simply open \`index.html\` in your browser:

\`\`\`bash
# Using Python
python -m http.server 8000

# Using Node.js
npx serve

# Or just double-click index.html
\`\`\`

## Project Structure

\`\`\`
.
├── index.html           # Main page
├── styles.css           # Global styles
└── *.html               # Additional pages
\`\`\`

## Features

- Pure HTML/CSS - no build step required
- Tailwind CSS via CDN
- Responsive design
- Ready to deploy anywhere

## Deployment

You can deploy this project to any static hosting service:

- GitHub Pages
- Netlify
- Vercel
- AWS S3
- Any web server

## Customization

Edit the HTML files directly or modify \`styles.css\` for custom styling.
`;
  }
}

// Type import for GeneratedFile
type GeneratedFile = {
  path: string;
  content: string;
  language: string;
};
