/**
 * Nuxt 3 Vue SFC Code Generator
 */

import type { Block, Page, Design } from '@open-design/blocks';
import { BaseCodeGenerator } from './base-generator.js';
import {
  generateVueTemplate,
  generatePropsInterface,
  extractTailwindClasses,
  generateComponentName,
} from '../utils/code-utils.js';
import { injectVueBlockIds } from '../utils/block-id-injection.js';
import type { CodeGenerationResult, FrameworkTarget } from '../types/index.js';

/**
 * Nuxt 3 code generator
 */
export class NuxtCodeGenerator extends BaseCodeGenerator {
  readonly framework: FrameworkTarget = 'nuxt';

  /**
   * Generate code for a single page
   */
  generatePage(page: Page): CodeGenerationResult {
    const componentName = generateComponentName(page.name);
    const fileName = this.generateFilePath(page.name, '.vue');
    
    // Generate Vue SFC
    const sfcContent = this.generateVueSFC(page.blocks, componentName);
    
    return {
      files: [
        this.createFile(fileName, sfcContent, 'vue'),
      ],
      entryFile: fileName,
      framework: 'nuxt',
    };
  }

  /**
   * Generate code for a full design
   */
  generateDesign(design: Design): CodeGenerationResult {
    const files: GeneratedFile[] = [];
    
    // Generate each page
    for (const page of design.pages) {
      const pageResult = this.generatePage(page);
      files.push(...pageResult.files);
    }
    
    // Generate app.vue
    const appVue = this.generateAppVue(design.pages);
    files.push(this.createFile('app.vue', appVue, 'vue'));
    
    // Generate nuxt.config.ts
    const nuxtConfig = this.generateNuxtConfig();
    files.push(this.createFile('nuxt.config.ts', nuxtConfig, 'typescript'));
    
    // Generate package.json
    const packageJson = this.generatePackageJson(design.name);
    files.push(this.createFile('package.json', packageJson, 'json'));
    
    // Generate README.md
    const readme = this.generateReadme(design.name);
    files.push(this.createFile('README.md', readme, 'markdown'));
    
    return {
      files,
      entryFile: 'app.vue',
      framework: 'nuxt',
    };
  }

  /**
   * Generate code for a single block
   */
  generateBlock(block: Block): string {
    return generateVueTemplate([block]);
  }

  /**
   * Generate Vue SFC content
   */
  private generateVueSFC(blocks: Block[], componentName: string): string {
    let template = generateVueTemplate(blocks);
    
    // Inject block IDs for visual editing
    template = injectVueBlockIds(template, blocks);
    
    const props = this.extractProps(blocks);
    const propsInterface = Object.keys(props).length > 0
      ? generatePropsInterface(props)
      : '';

    return `<script setup lang="ts">
${propsInterface ? propsInterface + '\n\n' : ''}defineProps<{
  // Component props
}>();
</script>

<template>
  <div>
${template.split('\n').map(line => '    ' + line).join('\n')}
  </div>
</template>

<style scoped>
/* Add custom styles here */
</style>
`;
  }

  /**
   * Generate app.vue
   */
  private generateAppVue(pages: Page[]): string {
    return `<script setup lang="ts">
// Root application component
</script>

<template>
  <NuxtPage />
</template>

<style>
/* Global styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: system-ui, -apple-system, sans-serif;
}
</style>
`;
  }

  /**
   * Generate nuxt.config.ts
   */
  private generateNuxtConfig(): string {
    return `// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
  css: ['~/assets/css/main.css'],
  tailwindcss: {
    configPath: 'tailwind.config.ts',
  },
});
`;
  }

  /**
   * Generate package.json
   */
  private generatePackageJson(projectName: string): string {
    const pkg = {
      name: projectName.toLowerCase().replace(/\s+/g, '-'),
      private: true,
      type: 'module',
      scripts: {
        build: 'nuxt build',
        dev: 'nuxt dev',
        generate: 'nuxt generate',
        preview: 'nuxt preview',
        postinstall: 'nuxt prepare',
      },
      dependencies: {
        nuxt: '^3.11.0',
        vue: '^3.4.21',
        'vue-router': '^4.3.0',
      },
      devDependencies: {
        '@nuxtjs/tailwindcss': '^6.11.4',
        typescript: '^5.4.2',
      },
    };
    
    return JSON.stringify(pkg, null, 2);
  }

  /**
   * Generate README.md
   */
  private generateReadme(projectName: string): string {
    return `# ${projectName}

Generated by Open Design

## Setup

Make sure to install the dependencies:

\`\`\`bash
npm install
\`\`\`

## Development Server

Start the development server on \`http://localhost:3000\`:

\`\`\`bash
npm run dev
\`\`\`

## Production

Build the application for production:

\`\`\`bash
npm run build
\`\`\`

Locally preview production build:

\`\`\`bash
npm run preview
\`\`\`

## Project Structure

\`\`\`
.
├── app.vue              # Root component
├── nuxt.config.ts       # Nuxt configuration
├── package.json         # Dependencies
└── pages/               # Page components
    └── *.vue
\`\`\`
`;
  }

  /**
   * Extract props from blocks
   */
  private extractProps(blocks: Block[]): Record<string, any> {
    const props: Record<string, any> = {};
    
    const traverse = (block: Block) => {
      // Extract props from block
      Object.entries(block.props).forEach(([key, value]) => {
        if (value !== undefined && value !== null && value !== '') {
          props[key] = value;
        }
      });
      
      // Traverse children
      block.children.forEach(traverse);
    };
    
    blocks.forEach(traverse);
    return props;
  }
}

// Type import for GeneratedFile
type GeneratedFile = {
  path: string;
  content: string;
  language: string;
};
